routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NotificationController;

use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','frontpageController@index');
Route::middleware(['checkapitoken'])->group(function () {
Route::get('/dashboard','frontpageController@dashboard')->name('customerdashboard');
Route::get('/invoicedetail/{id}','frontpageController@invoicedetail')->name('invoicedetail');
Route::get('/customer/profile','FrontCustomerController@UserProfile')->name('profile');
Route::post('/customer/updateprofile','FrontCustomerController@UserUpdateProfile')->name('customerupdateprofile');
Route::get('/customer/orders','FrontCustomerController@orders')->name('orders');
Route::get('/customer/invoices','FrontCustomerController@invoices')->name('invoices');
});
Route::get('/{slug}/{post_type?}','frontpageController@page')->where('post_type', 'page|testimonial|partner');
Route::get('/service/{slug}','frontpageController@serviceDetails');
Route::get('/blog/{slug}','frontpageController@blogDetails');
Route::get('/order/neworder','FrontOrderController@showOrderFrom')->name('order');
Route::get('/order/getaddress','FrontOrderController@getAddress')->name('getwebaddress');
Route::get('/order/getdeliverydate','FrontOrderController@getDeliveryDate')->name('getdelivery');
Route::get('/order/getdeliverydatetime','FrontOrderController@getDeliveryTime')->name('getdeliverytime');
Route::post('/saveorder','FrontOrderController@saveOrder')->name('saveorder');
Route::get('/order/getcollectiontime','FrontOrderController@getCollectionTime')->name('getcollectiontime');
Route::get('/price','frontpageController@page');




Route::get('/admin/login', function () {
    return view('auth.login');
})->name('login');

Route::get('/admin', function () {
    return redirect()->to('login');
})->name('login');

Auth::routes();
Route::get('admin/logout', function ()
{
    auth()->logout();
    Session()->flush();

    return Redirect::to('admin/login');
})->name('logout');

Route::get('/customer/register','AuthController@Register')->name('show-register');
Route::get('/customer/login','AuthController@Login')->name('show-login');

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function(){
    //Auth::routes();
   
    Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard');

    /**CNS Notifications*/
    Route::get('/HideNotify', 'NotificationController@HideNotify')->name('HideNotify');
    /**CNS */
	
    Route::post('/setrole', 'Admin\DashboardController@setRole')->name('setrole');
    Route::resource('/settings', 'Admin\SettingsController');
    Route::resource('/services', 'Admin\ServicesController');
    Route::get('/getchildservice', 'Admin\ItemController@getSubService')
        ->name('getsubservice');
    Route::get('/services/delete/{id}', 'Admin\ServicesController@destroy')
        ->name('services.destroy');
    Route::resource('/servicearea', 'Admin\ServiceAreaController');
    Route::get('/servicearea/delete/{id}', 'Admin\ServiceAreaController@destroy')
        ->name('servicearea.destroy');
    Route::resource('/pages', 'Admin\PagesController');
    Route::get('/pages/delete/{id}', 'Admin\PagesController@destroy')
        ->name('pages.destroy');
    Route::resource('/blogs', 'Admin\BlogsController');
    Route::get('/blogs/delete/{id}', 'Admin\BlogsController@destroy')
        ->name('blogs.destroy');
    Route::resource('/orders', 'Admin\OrdersController');
    Route::resource('/users', 'Admin\UsersController');

    Route::get('/assignrole/{id}', 'Admin\RoleUserController@assignRole')->name('assignrole');
    Route::post('/saverole', 'Admin\RoleUserController@saveRole')->name('saverole');

    Route::get('modules/assignroletomodule', 'Admin\RoleModuleController@assignRoleToModule')->name('assignroletomodule');
    Route::post('modules/saveroletomodule', 'Admin\RoleModuleController@saveRoleToModule')->name('saveroletomodule');
    
    Route::get('/user/showprofile/{id}', 'Admin\UsersController@showProfile')->name('showprofile');
    Route::post('/user/updateprofile', 'Admin\UsersController@updateProfile')->name('updateprofile');
    
    Route::resource('/items', 'Admin\ItemController');
    Route::get('/items/delete/{id}', 'Admin\ItemController@destroy')
        ->name('items.destroy');

    Route::resource('/testimonials', 'Admin\TestimonialsController');
    Route::get('/testimonials/delete/{id}', 'Admin\TestimonialsController@destroy')
    ->name('testimonials.destroy');

    Route::resource('/partners', 'Admin\PartnerLogoController');
    Route::get('/partners/delete/{id}', 'Admin\PartnerLogoController@destroy')
    ->name('partners.destroy');
    // Route::get('/subscription/create', ['as'=>'home','uses'=>'Admin\SubscriptionController@index'])->name('subscription.create');
// Route::post('order-post', ['as'=>'order-post','uses'=>'Admin\SubscriptionController@orderPost']);
});

app/Http/Controllers/Admin/ItemController.php
<?php

namespace App\Http\Controllers\Admin;
// session_start();
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Item;
use App\Model\Service;
use Session;
use Redirect;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::with('service')->get();
        return view('admin.items.index')->with(['items'=>$items]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $services = Service::select('id','name')->get();
        return view('admin.items.create')->with(['services'=>$services]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $item_image ='';
        //File upload
         if($request->hasFile('item_image')){
            $photo = $request->file('item_image');
            $new =  $photo->getClientOriginalName();
            $photo->move(public_path('images/services/items'), $new);
            $item_image = $new;
        };
        $itemArray = array(
            'name'=>$request->name,
            'service_id'=> !empty($request->services) ? $request->services : '',
            'item_image'=>$item_image,
            'status'=>1,
            'customer_price'=>$request->customer_price
        );

        //dd($itemArray);
        //Create Service
       $item = Item::Create(
            $itemArray 
        );
    return redirect('/admin/items')->with('message', 'Item has been created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $services = Service::select('id','name')->get();
        $item = Item::where('id',$id)->get()->first();
        return view('admin.items.update')->with(['item'=>$item,'services'=>$services]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Update the data
        $item_image ='';
        //File upload
         if($request->hasFile('item_image')){
            $photo = $request->file('item_image');
            $new =  $photo->getClientOriginalName();
            $photo->move(public_path('images/services/items'), $new);
            $item_image = $new;
        };
        $item = Item::find($id);
        $item->name       = $request->name;
        if(!empty($item_image))
        $item->item_image = $item_image;
        if(!empty($request->services)) 
        $item->service_id       = $request->services;
        $item->customer_price       = $request->customer_price;
        $item->facility_price       = $request->facility_price;
        $item->status = $request->status;
        $item->save();
        // redirect
        Session::flash('message', 'Successfully updated item!');
        return Redirect::to('admin/items');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Item::find($id)->delete())
        {
            return redirect('/admin/items')->with('message', 'Item has been deleted successfully');
        } else {
            return redirect('/admin/items')->with('message', 'There is some problem');
        }
    }

    public function getSubService(Request $request){
        $service = $request->service;
        $services = Service::where('parent_id',$service)->get();
        $servicedata = [];
        if(!empty($services)) 
            return response()->json($services);
        else
            return response()->json($servicedata);
    }
}

resources/views/admin/items/create.blade.php
@extends('layouts.master')

@section('content')
 <!-- Content Header (Page header) -->
 <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Add Items</h1>
          </div><!-- /.col -->
          <div class="col-sm-6 text-right">
            <button onclick="window.history.back()" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Go Back</button>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="card card-primary card-outline">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fas fa-edit"></i>
                  Location Detail
              </h3>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-sm-3">
                <form enctype="multipart/form-data" action="{{route('items.store')}}" method="post">
                 @csrf
                  <div class="form-group">
                    <div class="row">
                      <div class="col-md-6">
                        <label for="exampleInputEmail1">Name</label>
                        <input type="text" required="" class="form-control" id="exampleInputEmail1" name="name" value="{{old('name')}}" placeholder="Enter Item Name" maxlength="30">
                      </div>
                      <div class="col-md-6">
                        <label for="exampleInputEmail1">Customer Price</label>
                        <input type="number" required="" class="form-control" id="exampleInputEmail1" name="customer_price" value="{{old('customer_price')}}" placeholder="Enter Item Customer Price">
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="row">
                    <div class="col-md-6">
                    <label for="exampleSelectBorder">Choose Service</label>
                    <select name="services" required="" class="custom-select form-control">
                      <option value="">Please Select</option>
                      @foreach($services as $serviceKey=>$serviceVal)
                      <option value="{{old('services',$serviceVal->id)}}" >{{$serviceVal->name}}</option>
                      @endforeach
                    </select>
                    </div>
                    <div class="col-md-6">
                    <label for="exampleSelectBorder">Select Icons</label>
                    <input name="item_image" type="file" class="custom-select form-controlr">
                    </div>
                  </div>
                  </div>
                  <div class="text-right">
                  <button type="submit" name="add_item" class="btn btn-primary"><i class="fa fa-save"></i> Add Item</button>
                </div>
                </form>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
@endsection

resources/views/admin/items/index.blade.php
@extends('layouts.master')

@section('content')
@php $roleId = App\Model\RoleUser::where('id',Auth::user()->id)->pluck('role_id')->first(); @endphp
@php $roleName = App\Model\Role::where('id',$roleId)->pluck('name')->first();@endphp

 <!-- Content Header (Page header) -->
 <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Items</h1>
          </div><!-- /.col -->
          <div class="col-sm-6 text-right">
            <a href="{{ route('items.create')}}" class="btn btn-success">Add Item +</a>
            <button onclick="window.history.back()" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Go Back</button>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
     <!-- Main content -->
     <section class="content">
      <div class="container-fluid">
      @if (session('message'))
          <div class="alert alert-success">
              {{ session('message') }}
          </div>
      @endif
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Items</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                @if($roleId == 2) 
                <table id="items" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>#SR No.</th>
                    <th>Item Name</th>
                    <th>Service</th>
                    <th>Customer Price</th>
                    <th>Facility Price</th>
                    <th>Icon</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                    @php  $i=1; @endphp
                    @if(!empty($items) && count($items) > 1)
                    @foreach($items as $item)
                    <tr>
                      <td>{{ $i++ }}</td>
                      <td>{{$item->name}}
                      </td>
                      <td>{{$item->service->name}}</td>
                      <td>{{$item->customer_price}}</td>
                      <td>{{$item->facility_price}}</td>
                      <td><img src="{{url("images/services/items/$item->item_image")}}" height="80" width="80" /></td>
                      <td>
                  
                      <a href="{{route('items.edit',$item->id)}}" class="btn btn-xs btn-primary"><i class="fa fa-pencil-alt"></i></a>
                      <!--<a href="{{route('items.show',$item->id)}}" class="btn btn-xs btn-info"><i class="fa fa-eye"></i></a>-->
                      <a role="button" data-toggle="modal" data-target="#modal-default<?=$item->id?>" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>
                      </td>
                    </tr>
                    <div class="modal fade" id="modal-default<?=$item->id?>">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title">Delete Item</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                      <form action="{{ route('items.destroy', $item->id) }}" method="get">
                          <p>Are you sure you want to proceed ?</p>
                        </div>
                        <div class="modal-footer justify-content-between">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary">Yes</button>
                        </div>
                      </form>
                    </div>
                    <!-- /.modal-content -->
                  </div>
                  <!-- /.modal-dialog -->
                </div>
                  @endforeach
                  @elseif(count($items) == 1)
                  <tr>
                  <td>{{ $i++ }}</td>
                      <td>{{$items[0]->name}}
                      </td>
                      <td>{{$items[0]->service->name}}</td>
                      <td>{{$items[0]->customer_price}}</td>
                      <td>{{$items[0]->facility_price}}</td>
                      <td><img src="{{url("images/services/items/$items[0]->item_image")}}" height="80" width="80" /></td>
                      <td>
                  
                      <a href="{{route('items.edit',$items[0]->id)}}" class="btn btn-xs btn-primary"><i class="fa fa-pencil-alt"></i></a>
                      <!--<a href="{{route('items.show',$items[0]->id)}}" class="btn btn-xs btn-info"><i class="fa fa-eye"></i></a>-->
                      <a role="button" data-toggle="modal" data-target="#modal-default<?=$items[0]->id?>" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>
                      </td>
                    </tr>
                    <div class="modal fade" id="modal-default<?=$items[0]->id?>">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title">Delete Item</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                      <form action="{{ route('items.destroy', $items[0]->id) }}" method="get">
                          <p>Are you sure you want to proceed ?</p>
                        </div>
                        <div class="modal-footer justify-content-between">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary">Yes</button>
                        </div>
                      </form>
                    </div>
                    <!-- /.modal-content -->
                  </div>
                  <!-- /.modal-dialog -->
                </div>
                  @endif
                  </tfoot>
                </table>
              @elseif($roleId == 1)
                <table id="items" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>#SR No.</th>
                    <th>Item Name</th>
                    <th>Service</th>
                    <!--<th>Customer Price</th>-->
                    <th>Facility Price</th>
                    <th>Icon</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                    @php  $i=1; @endphp
                    @if(!empty($items) && count($items) > 1)
                    @foreach($items as $item)
                    <tr>
                      <td>{{ $i++ }}</td>
                      <td>{{$item->name}}
                      </td>
                      <td>{{$item->service->name}}</td>
                      <!--<td>{{$item->customer_price}}</td>-->
                      <td>{{$item->facility_price}}</td>
                      <td><img src="{{url("images/services/items/$item->item_image")}}" height="80" width="80" /></td>
                      <td>
                  
                      <a href="{{route('items.edit',$item->id)}}" class="btn btn-xs btn-primary"><i class="fa fa-pencil-alt"></i></a>
                      <!--<a href="{{route('items.show',$item->id)}}" class="btn btn-xs btn-info"><i class="fa fa-eye"></i></a>-->
                      <a role="button" data-toggle="modal" data-target="#modal-default<?=$item->id?>" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>
                      </td>
                    </tr>
                    <div class="modal fade" id="modal-default<?=$item->id?>">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h4 class="modal-title">Delete Item</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                          <form action="{{ route('items.destroy', $item->id) }}" method="get">
                              <p>Are you sure you want to proceed ?</p>
                            </div>
                            <div class="modal-footer justify-content-between">
                              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                              <button type="submit" class="btn btn-primary">Yes</button>
                            </div>
                          </form>
                        </div>
                        <!-- /.modal-content -->
                      </div>
                      <!-- /.modal-dialog -->
                    </div>
                  @endforeach
                  @elseif(count($items) == 1)
                  <tr>
                  <td>{{ $i++ }}</td>
                      <td>{{$items[0]->name}}
                      </td>
                      <td>{{$items[0]->service->name}}</td>
                      <!--<td>{{$items[0]->customer_price}}</td>-->
                      <td>{{$items[0]->facility_price}}</td>
                      <td><img src="{{url("images/services/items/$items[0]->item_image")}}" height="80" width="80" /></td>
                      <td>
                  
                      <a href="{{route('items.edit',$items[0]->id)}}" class="btn btn-xs btn-primary"><i class="fa fa-pencil-alt"></i></a>
                      <!--<a href="{{route('items.show',$items[0]->id)}}" class="btn btn-xs btn-info"><i class="fa fa-eye"></i></a>-->
                      <a role="button" data-toggle="modal" data-target="#modal-default<?=$items[0]->id?>" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>
                      </td>
                    </tr>
                    <div class="modal fade" id="modal-default<?=$items[0]->id?>">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h4 class="modal-title">Delete Item</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                          <form action="{{ route('items.destroy', $items[0]->id) }}" method="get">
                              <p>Are you sure you want to proceed ?</p>
                            </div>
                            <div class="modal-footer justify-content-between">
                              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                              <button type="submit" class="btn btn-primary">Yes</button>
                            </div>
                          </form>
                        </div>
                        <!-- /.modal-content -->
                      </div>
                      <!-- /.modal-dialog -->
                    </div>
                  @endif
                  </tfoot>
                </table>
              @else
              @endif
              </div>
              <!-- /.card-body -->
            </section>
@endsection
@section('footer-scripts')
  <script>
      $(function () {
        $('#items').DataTable({
          "paging": true,
          "pageLength": 10,
          "lengthChange": false,
          "searching": true,
          "ordering": true,
          "info": true,
          "autoWidth": false,
          "responsive": true,
        });
      });
  </script>
@endsection

   

resources/views/admin/items/update.blade.php
@extends('layouts.master')

@section('content')
@php $roleId = App\Model\RoleUser::where('id',Auth::user()->id)->pluck('role_id')->first(); @endphp
@php $roleName = App\Model\Role::where('id',$roleId)->pluck('name')->first();@endphp

 <!-- Content Header (Page header) -->
 <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Update Item</h1>
          </div><!-- /.col -->
         <div class="col-sm-6 text-right">
            <button onclick="window.history.back()" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Go Back</button>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="card card-primary card-outline">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fas fa-edit"></i>
                  Item Detail
              </h3>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-sm-3">
                <form enctype="multipart/form-data" action="{{route('items.update',$item->id)}}" method="post">
                 @csrf
                 {{ method_field('PUT') }}
                  <div class="form-group">
                    <div class="row">
                      <div class="col-md-6">
                        <label for="exampleInputEmail1">Name</label>
                        <input type="text" required="" class="form-control" id="exampleInputEmail1" name="name" value="{{old('name',$item->name)}}" placeholder="Enter Item Name">
                      </div>
                      @if($roleId == 2)
                      <div class="col-md-6">
                        <label for="exampleInputEmail1">Customer Price</label>
                        <input type="text" required="" class="form-control" id="exampleInputEmail1" name="customer_price" value="{{old('customer_price',$item->customer_price)}}" placeholder="Enter Item Customer Price">
                      </div>
                      @else
                      @endif
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="row">
                      <div class="col-md-6">
                        <label for="exampleInputEmail1">Facility Price</label>
                        <input type="text" required="" class="form-control" id="exampleInputEmail1" name="facility_price" value="{{old('facility_price',$item->facility_price)}}" placeholder="Enter Facility Price">
                      </div>
                      <div class="col-md-6">
                        <label for="exampleInputEmail1">Item In Count</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" name="item_no" value="{{old('item_no',$item->item_no)}}" placeholder="Enter Item Numbers">
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="row">
                    <div class="col-md-6">
                    <label for="exampleSelectBorder">Choose Service</label>
                    <select name="services" required="" class="custom-select form-control-border">
                      <option value="">Please Select</option>
                      @foreach($services as $serviceKey=>$serviceVal)
                      <option value="{{old('services',$serviceVal->id)}}" @if(isset($item->service_id) && $item->service_id == $serviceVal->id) selected @endif >{{$serviceVal->name}}</option>
                      @endforeach
                    </select>
                    </div>
                    <div class="col-md-6">
                    <label for="exampleSelectBorder">Choose Status</label>
                    <select name="status" class="custom-select form-control-border">
                      <option value="">Please Select</option>           
                      <option value="{{old('status',1)}}" @if(isset($item->status) && $item->status == 1) selected @endif >yes</option>
                      <option value="{{old('status',0)}}" @if(isset($item->status) && $item->status == 0) selected @endif>No</option>
                    </select>
                    </div>
                  </div>
                  </div>
                  <button type="submit" name="update_item" class="btn btn-primary">Update Item</button>
                </form>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
@endsection